### ISSUE TITLE
Google API Client Deprected

### ISSUE THREAD

**Issue by Scienticious** [googlesamples/android-DataLayer#4]
Google Api Client  is depreceted in latest Wearable play service , what is the alternative .
Currently i am using 
'com.google.android.gms:play-services-wearable:15.0.1'
      

Mentioned below code is working but it is deprected
mGoogleApiClient = new GoogleApiClient.Builder(this)
                .addApi(Wearable.~~API~~)
                .build();
        mGoogleApiClient.connect();

**Comment by codingjeremy** [comment]
Revamped the whole thing to use latest APIs, thanks for the catch!
