### ISSUE TITLE
Extension of dealing with broken connection between wearable- and handheld nodes

### ISSUE THREAD

**Issue by yingding** [googlesamples/android-DataLayer#6]
## Feature Request
Since sometime it is not desired to send data or messages between the wearable and handheld devices in case the (1) bluetooth/wifi connection is off on the phone, (2) watch disconnected in WearOs App, or (3) bluetooth/wifi connection is off on the watch.

The onCapabilityChanged method can be modified to catch the connection status via the available remote nodes by the given capability name. If the reachable wear nodes is empty set, than the data and message exchange can be pause to save RAM and Battery. After the connection between the nodes are reestablished, the data and message exchange shall go on.

**Comment by codingjeremy** [comment]
This issue has been migrated to the new Wear OS sample repo, so I am closing this here.
